version: '3.8'
services:
  postgres:
    image: postgres:10.3
    container_name: db
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=$DB_POSTGRES_USER
      - POSTGRES_PASSWORD=$DB_POSTGRES_PASSWORD
    volumes:
      - postgres_db:/vars/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres_db:
